name: 🐞 Bug Report
description: File a bug/issue
title: ""
labels: ["bug", "triage", "needs testing"]
body:
  - type: textarea
    attributes:
      label: Environment
      description: |
         - Where did this bug occur on?
         - Provide information about the device the bug happened on. (If this was a website bug report you should provide the browser used, its version and your screen size)
        examples:
          - **OS**: Windows 10
          - **Browser**: Firefox 95.0 (64-bit)
          - **Platform**: In-game
      value: |
          - Platform: 
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Bug Description
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What was supposed to happen? If you are not sure, please state so.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: What did you do to make this problem happen? Try to be as thorough as possible.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Extras
      description: |
        Do you have anything else to add?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Have I read and agree to the [README](https://github.com/Minefly/minefly#readme)?
      options:
      - label: I have read and agree to the [README](https://github.com/Minefly/minefly#readme)
        required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure you've completed all the steps in the checklist
      options:
      - label: I am not reporting a security vulnerability (A vulnerability that, were it to be exploited, would cause damage to confidentiality, integrity, or availability.)
        required: true
      - label: I have read and agree to the [README](https://github.com/Minefly/minefly#readme)
        required: true
      - label: I have made sure this issue is not a duplicate
        required: true
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have made sure this issue is not a duplicate
        required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
